### ISSUE TITLE
Allow skipping repo/packages to verify

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/luet-cosign#6]
Currently if you use more than 1 repo in luet that is not signed  you cannot verify the full chain as it would fail to verify one of the repos and it will fail the whole install.

We should provide a way of skipping repos to verify to support more than 1 repo in luet.

## solutions 

 - Have a COSIGN_SKIP env var -> straightforward but kind of crappy
 - Read the luet config and check if the repo has a `cosign:true` value? -> Best solution but requires proper docs for derivatives!

**Comment by mudler** [comment]
Also on this, few ideas:

- we can have COSIGN_ENFORCE=1 (or COSIGN_STRICT, etc.) to enforce cosigning of all images and fail if signatures are not found. We can then think about not erroring if we don't find signatures (still the user should be able to set this)
- COSIGN_ENFORCE_IMAGES to enforce cosign only on the image pulls references that are matching (e.g. a list of image names to enclude in the check, without the tags)

**Comment by Itxaka** [comment]
yikes.

I like the idea of enforce and skip both as its easier to manage (like allow/deny lists, easy for the user to set whatever they want)

The permissive/strcit one...I really dont like it as it usually ends being set to permissive for all eternity (ask selinux lmao) instead of kind of forcing the nd user to properly use the application, instead of setting the application to on but ignore any errors.


Anyway, I think I'll first go with the allow/deny list as it seems the most flexible one.

**Comment by mudler** [comment]
> The permissive/strcit one...I really dont like it as it usually ends being set to permissive for all eternity (ask selinux lmao) instead of kind of forcing the nd user to properly use the application, instead of setting the application to on but ignore any errors.
> 
> Anyway, I think I'll first go with the allow/deny list as it seems the most flexible one.

:+1:
